---
title: "pttR 備忘稿"
author: "廖永賦"
date: "September 28, 2018"
output:
  html_document:
    css: /home/liao/local_depend/style_sheets/style.css
---


## 首頁 | 1

<br>
**投影片連結**
<br>

閒聊：  
今天要**介紹 pttR**，一個 R 套件  
我是在**八月初**的時候開始寫這個套件  
在那之前，我**完全沒有碰過 R 套件開發**這塊。  
所以我以為會**花很久的時間**才能上手。  
但結果**比想像中的容易很多**。  

## 巨人的肩膀 | 2

這都要感謝 Hadley Wickham 寫的這本書，  
這應該是我看過 **cp 值最高的電腦書**，  
我先花了 **3 天**看完這本**不到200頁**s書，  
之後**撰寫套件的過程**都很順利  

**(Next)**  
然後，這本書提到一個很**有趣**的想法  
就是 R 套件的架構不僅可用在軟體開發，
也**可以用來組織工作流程**，  
這樣就不需要為**檔案管理**而傷腦筋，  
而且也可以直接**將成果透過安裝套件的方式分享**給他人。  

這篇文章就說明如何把 R 套件的架構運用在資料分析上。  

## Outline | 3

- 第一部份  
    **簡單介紹** pttR，並且會**實際操作幾個函數**

- 第二部份  
    介紹 **pttR 內部**用到的**斷詞詞庫**

## pttR | Section

None

## pttR 目標 | 5

- pttR 當前的目標是**協助**使用者**取得和處理 PTT 資料**  
- 因為是第一次寫套件，不敢把套件的**規模設得太過巨大**，  
- 所以現階段的 pttR 就是以這 3 個目標去構想的  

**(Next)**  
簡單來說，

- 將「原始資料(網頁)」轉換成「其它 text mining 套件的 corpus object」  

## How pttR Works | 6 {.smaller}

- 這張**流程圖**是我對於 pttR **該如何運作**的**想像**  
- 圖中可以分成 **3 個部份**，正好對應到**前一張投影片**的 3 個目標  

## Get Started | 7 {.smaller}

- 接下來我會**一邊實際操作一邊用投影片**  
- 大家可以用最上面的**程式碼下載 pttR**  
- 下方的「範例程式碼」則大致是上一張**流程圖寫成 code** 的樣子  


## 資料抓取 | 8 {.smaller}

- pttR 是從**批踢踢網頁版**抓資料

**(Next)**

- `index2df()` 以及 `post2df()` 是將**網頁轉換成 data frame** 的兩個函數
- 可以將這兩個**函數的回傳值**想像成**網頁頁面**，只是網頁的資訊**濃縮成 data frame**而已

**(Open 1st link) --> nav to (Gossiping/index)**

- **`index2df()`** 就是**從這個頁面抓取資料**

**(Demo index2df)**

---

**(Back to Web) --> (Copy Post Link)**

- **`post2df()`** 則是從**某篇文章頁面**抓取資料

**(Demo post2df() 1 post)**

- 因為**文章的結構**比較**複雜**，所以`post2df()`回傳的 **data frame 結構**也比較**複雜**

- `comment` 這個 column 是一個 **list-column**，它**每個 cell** 裡不是一個值，而是一個 data frame。

    
**(Demo post2df() mult posts)**

- `post2df()` 除了吃**單一網址**外，也可以吃**一個 vector** 的「網址」
    - 可以**與`index2df()`合用**


## 斷詞 | 9 {.smaller}

- pttR 的斷詞函數是直接去**包 jiebaR 的函數**

- jiebaR 有提供**使用者自訂辭庫**的功能
    - pttR 的**函數就是使用「自訂辭庫」加入 PTT 用語**，  
    - **詞庫來源**之後會介紹

**(Next)**

- 這邊**斷詞函數的設計**，讓函數可以使用 **tidyverse** 的寫法


**(Open Demo Post Link) --> (Demo Segmentation 1)**


**(Demo Segmentation 2)**

- 如果不滿意斷詞結果，可以自行**添加詞彙**


## 批踢踢詞庫 | Section {.smaller}

最後兩個將 data frame 轉換為成 **Corpus object** 的**函數**  
因為時間的關係，這裡就略過，  
這些函數使用上就只有一行，  
有興趣的人可以自己試看看  

那接下來介紹前面**斷詞函數**用到的 **PTT 詞庫**  

## 鄉民百科資料擷取 | 11 {.smaller}

因為我並**不是鄉民**  
所以在寫這個套件的時候，在網路上**搜尋不懂的 PTT 用語**時，**發現「PTT鄉民百科」**這個網站。  

**(Open [PTT鄉民百科]())**  
這網站在 **2014 年創立**，至今都還有在更新  
正好可以當作 PTT 用語的**來源**  

**(Nav to any Wiki)**  
這邊是用 **Python 的 Scrapy Framework** 去爬鄉民百科，  
擷取下來的文字，有 **4 種**來源  
標題、粗體、引號、紅色超連結  
大家可以點投影片上**PTT用語**連結去看擷取下來的文字  

## 自動更新 | 12 {.smaller}

因為 PTT 鄉民百科會不定期新增頁面  
所以這邊透過 Travis CI **每個月**，重新爬取鄉民百科  
再將更新的資料傳到 **GitHub gh-pages** 這個 branch 上  

pttR 斷詞函數的**內建詞庫**，  
會在每次新的 commit push 到 GiHub 時，  
透過 Travis CI 自動更新於 **build 這個 branch**

